### ISSUE TITLE
Game Not Starting

### ISSUE THREAD

**Issue by ReZeroPlat** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#10]
I'm having another problem, the controller connects, exits the pairing screen, opens the game and stops pressing "A", after some time closes the game and reopens it and restarts this loop. Screen is set to 100%

**Comment by Dinones** [comment]
Can you answer these questions:

1. What game are you playing?
2. What are the FPS of the program?
3. What state is the program when it enters the game?
4. What option of the Shiny Hunter are you running?
5. What pokemon are you trying to catch?

**Comment by ReZeroPlat** [comment]
The game is Pokemon Brilliant Diamond
4 Fps
Restart_Game_1
Static Encounter
Latias

**Comment by Dinones** [comment]
1. Regarding de FPS, they are very low, did you add the capture card as explained in the instructions as a "Webcam" instead of an "USB Device" as seen in the image?

![image](https://github.com/user-attachments/assets/178b0154-9d29-4abb-b9cb-872a0084d780)

If not, please do it. If yes, can you tell me the FPS you get by running `python3 GUI.py` and selecting the option *Open GUI using capture card*?

2. Not about the Latias, can you confirm you are right in front of the Latias and the player just need to press 'A' to enter the combat?
3. I need to know what is thre previous state before getting to the `RESTART_GAME_1` one.

**Comment by ReZeroPlat** [comment]
the problem is that I never had the "webcam" option under "usb". For Latias yes, they are precisely in front

**Comment by ReZeroPlat** [comment]
I solved it, I had to install the extension pack, now the fps are 30 and the game opens but as soon as it enters combat the program freezes because it says it has found a shiny even if it's not true, the status is: "Shiny_Found"

**Comment by Dinones** [comment]
Can you please send me the video the program records, please? It should be found in the Media/Videos/ folder.

**Comment by ReZeroPlat** [comment]
sure, this is the link

https://www.youtube.com/watch?v=kf54_Hw6jLM

**Comment by ReZeroPlat** [comment]
I also tried with rayquaza and the result is the same

**Comment by ReZeroPlat** [comment]
Isn't it possible to install the old shiny detection system?

**Comment by Dinones** [comment]
Hi! You will have the same problem with the previous version as the issue is on detecting specific pixels. There are two possible options:

1. Your program is working on a different frame rate thatn mine and it takes some extra ms to read frames.
2. Mayby your capture card is reading slightly different the colors of the game.

In order to see what is happening, could you please increase the value of  `SHINY_DETECTION_TIME` from 1 to 1.5 or 2 in the `Constants.py` file? If the error persists, then we are on the case number 2.

**Comment by ReZeroPlat** [comment]
yes, the problem persists. In any case I think I have the same game capture as you

**Comment by Dinones** [comment]
I think I found the issue. In the video you sent to me you can see before entering the latias combat the screen slightly flashes to a short white full screen (minute 0:38 of the video). Can you please tell me if by the end of this flash the state is ENTER_COMBAT_2?

**Comment by ReZeroPlat** [comment]
is, right after the flash the status is: ENTER_COMBAT_2

**Comment by ReZeroPlat** [comment]
updating the version of the program now freezes in front of the pokemon and then restarts

![VirtualBox_dinones_14_08_2024_16_30_19](https://github.com/user-attachments/assets/3f8bbd75-b940-4a26-9b90-1a45740058bf)

**Comment by Dinones** [comment]
Sorry, you are right, I forgot to change another script. Can you please try again?

**Comment by ReZeroPlat** [comment]
it finally seems to work, now all that remains is to find a shiny to confirm, thank you very much!!!

**Comment by Dinones** [comment]
Happy to hear that! Please tell me on discord if you find any pokémon. 

As a reminder, you chan execute the **check lost shiny** option of the `Image_processing.py` file to check if the program has skipped any shiny pokémon. It may calm you if it takes a lot of time to appear.
