### ISSUE TITLE
Game Keeps Resetting

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#15]
Instead of trying to go through the cutscenes to get the starter, it just goes and does a reset. Not sure what I'm doing wrong.

**Comment by RandomizerGamerRIPLinky** [comment]
Now it's stuck on waiting pair screen and won't continue

**Comment by RandomizerGamerRIPLinky** [comment]
It is still doing the reset. Not sure why. I didn't mess with the timing in the files.

**Comment by Dinones** [comment]
Sorry, could you please help me clarify what the issue is by answering these questions:

1. I understand you could install everything properly, and you passed all the tests explained [here](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Verify%20Installation.md), right?
2. When executing the `Shiny_Hunter.py` script, what state is it getting stuck in?

**Comment by Dinones** [comment]
Sorry, you are also reporting in this other thread "https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/13" that you get a blue screen when using the capture card. At this point, what is exactly your issue? Can you correctly get the images or just a blue screen? If you get the images, can you please answer the previous question I asked you?

- If the answer to the previous point is yes, when executing the Shiny_Hunter.py script, what state is it getting stuck in?

**Comment by RandomizerGamerRIPLinky** [comment]
I can't access the app anymore (The Virtual Camera app I used before), so I think this will just be closed for now as I'm unable to get past the blue screen and error spam
