### ISSUE TITLE
Detecting wrong Pokémon name

### ISSUE THREAD

**Issue by MCPika** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#20]
![image](https://github.com/user-attachments/assets/c38949d1-f6d4-4ebc-9cc9-6c4445b96fb4)

The text output states "Shiny Go found after X encounters" instead of "Shiny Turtwig found after X encounters"

The Constants.py was modified to deliver for the FR version so it should be "Tortipousse".
Same with the media saved Imgs + Videos they all are named "GO"

I'll be testing the EN version for Chimchar and see.

**Comment by Dinones** [comment]
Hi! Thank you for reporting! So happy you found a shiny Turtwig, _or "Tortipousse"_.

Can you please confirm whether changing the language to EN solves the issue or not?

**Comment by MCPika** [comment]
Hi no problem !
I do not know what name should the media files take when saved by the program? Right now they are named "Go Chimchar - XXXXXXXX"
I still didnt caught shiny chimchar so im not sure.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SoaringEagle93** [comment]
![360163183-0e11eb5a-a9e3-45cb-aec7-bde8eb219c6b](https://github.com/user-attachments/assets/b50ad7c9-3a76-4ebc-94b1-8e455049c35b)

Regirock shows as appeared as the pokemon name since the text for the encounter is "Regirock has appeared"

**Comment by David34920** [comment]
I've made a PR that fixes Pokemon name recognition for the French version: https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/pull/35

**Comment by Dinones** [comment]
Hi everyone! I have this issue in mind, but I'm getting quite busy with work, and it isn't a critical one. However, I have thought of a way to solve it without creating special cases for each language. My idea is to take the text string and split it into words. Here are some examples:

- **[EN]** "You encountered a wild Regirock!" --> ["**_Regirock_**", "has", "been", "found!"]
- **[FR]** "Un Regirock sauvage apparaît!" --> ["Un", "**_Regirock_**", "sauvage", "apparaît!"]
- **[ES]** "Ha aparecido un Regirock salvaje!" --> ["Ha", "aparecido", "un", "**_Regirock_**", "salvaje!"]
- [...]

In all cases, if you read the words from right to left, the first word that starts with a capital letter is the Pokémon name. I will implement this as soon as I can. That's why I didn't accept [David's pull request](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/pull/35/commits), which only solves it for French. I want to take the necessary time to ensure it works for every possible language of the game (except for the Asian ones).

**Comment by David34920** [comment]
Good Idea,
I have updated the PR with your proposal, feel free to adapt it to what you have in mind.

**Comment by Dinones** [comment]
Thank you for the implementation. I'll accept the pull request when I have time to make some changes, as I don't want it to be compatible with only 'FR', 'ES', and 'EN'. As mentioned, I want to take the necessary time to ensure it works for every possible language of the game.

**Comment by MCPika** [comment]
> Hi everyone! I have this issue in mind, but I'm getting quite busy with work, and it isn't a critical one. However, I have thought of a way to solve it without creating special cases for each language. My idea is to take the text string and split it into words. Here are some examples:
> 
> * **[EN]** "You encountered a wild Regirock!" --> ["**_Regirock_**", "has", "been", "found!"]
> * **[FR]** "Un Regirock sauvage apparaît!" --> ["Un", "**_Regirock_**", "sauvage", "apparaît!"]
> * **[ES]** "Ha aparecido un Regirock salvaje!" --> ["Ha", "aparecido", "un", "**_Regirock_**", "salvaje!"]
> * [...]
> 
> In all cases, if you read the words from right to left, the first word that starts with a capital letter is the Pokémon name. I will implement this as soon as I can. That's why I didn't accept [David's pull request](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/pull/35/commits), which only solves it for French. I want to take the necessary time to ensure it works for every possible language of the game (except for the Asian ones).

So @Dinones I've got yet some Pokemon names that are incorrect even in [ENG] - Mesprit is going for appeared :
![image](https://github.com/user-attachments/assets/deb319be-7472-4140-b878-15f992b9bfc5)

**Comment by Dinones** [comment]
Yes, this implementation _https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/20#issuecomment-2353121985_ should also solve the issue. I'll let you know when it's released. By the way, how are you trying to catch Mesprit if it spawns in a different location every time?

**Comment by MCPika** [comment]
> I'll let you know when it's released.

Ok I'm sorry I was so tired I've read between the lines ==


> By the way, how are you trying to catch Mesprit if it spawns in a different location every time?

So hear me out x') Normally Mesprit changes location every battle encounter with a pokemon so by looking for a randomn shiny I can encounter Mesprit and try to have it as well Shiny haha

**Comment by David34920** [comment]
Mesprit will always be the same, you have to kill it, beat the league to change his states and have a chance to have it shiny...
Same for Cresselia

**Comment by MCPika** [comment]
> Mesprit will always be the same, you have to kill it, beat the league to change his states and have a chance to have it shiny... Same for Cresselia

...You had to do it didn't you... you had to ruin the fun out of me !! hahaha well thats good to know I never knew that about mesprit....(Thats the first time im doing a shiny hunt so....)

**Comment by Dinones** [comment]
We have just uploaded a new version of the program that solves the pokémon name recognition for all non-Asian languages. 

In order to download the latest version, you can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.
