### ISSUE TITLE
Question about hunting Shiny Arceus?

### ISSUE THREAD

**Issue by cmr648** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#21]
Does this program work for hunting the Shiny Arceus even though it is "technically" not a static encounter? If so what mode should I set it to?

**Comment by Dinones** [comment]
Hi! Thank you for your comment! Yes, it is possible. 

I have pushed a new version of the program, please download the latest version. You can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder. 

In order to enable the one step forward before entering the combat, you should change the `MOVE_FORWARD_STATIC_ENCOUNTER` of the `Constants.py` script from `False` to `True`.

Right now, I'm not able to access the Arceus combat, so could you please confirm if it works?

**Comment by cmr648** [comment]
It literally seems to be working perfectly! Thank you!! I really appreciate it!

**Comment by Dinones** [comment]
Thank you! Enjoy your shiny hunting and your free time ;)
