### ISSUE TITLE
Starter hunter detecting false positive Starly

### ISSUE THREAD

**Issue by MCPika** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#28]
Hi Dino,
I don't know if you would categorize this as a bug or maybe an evolution to the program maybe? But I've encountered this as I'm still restarting for Chimchar (6k+). The program stopped because the shiny it encountered was Starly and so the database printed that interaction. Doesn't it feel wrong to stop the program in case its Starly that appears shiny instead of the starter? (I know it's gonna be 1/4096 but I'd feel that the program should just continue on?)

![image](https://github.com/user-attachments/assets/1e082e32-c97f-401a-a3ed-4ef10b045901)

**Comment by Dinones** [comment]
You probably did not find a shiny Starly. It sometimes gets bugged and detects the Starly instead of the starter, which will always raise a false positive due to the amount of time between the taxt boxes. I uploaded a new version of the program that solves this issue. The program will not stop if, when hunting a starter, it detects a Starly (it will if hunting for wild pokémons).

In order to download the latest version, you can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

**Comment by MCPika** [comment]
Well that's one fine job good I didn't know that could happen !! Thanks mate !!
But right now I can't wonder what would happen if Starly is shinny will the program detect it and stop? or just continue as it's not the starter?

**Comment by Dinones** [comment]
For now, if it finds a shiny Starly, it will just skip it and search for the shiny starter.
