### ISSUE TITLE
False Positive Starter

### ISSUE THREAD

**Issue by SNIELSEL** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#29]
when i start shiny hunting the starter it automatically counts a shiny around every 40/50 resets sometimes even faster.
video: https://www.youtube.com/watch?v=ST0nPiv8MYQ

the video doesnt show it but after 30 more seconds it goes to the joycon screen and shows in console that it found a shiny

the only mention i found of this was #28 but his issue is already solved in latest release.

I have shiny detection time set at 7 seconds

i also have the issue where when i return to my pc to check. the has been turned to sleep mode because the macro suddenly stopped. This for some reason only happens at night

could this have to do with the colors that my capture car displays like in #11 ?

**Comment by MCPika** [comment]
Yeah I was gonna post something too.
![image](https://github.com/user-attachments/assets/d1ccbed0-865c-4e08-ba9c-8a5fa8f20879)

**Comment by Dinones** [comment]
Hi! Sorry for the late response—I was away on a business trip. The issue you're experiencing, as you mentioned, is related to this:
- https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781

Could you please follow these steps and let me know the output you get? The problem is that each capture card detects slightly different pixel colors, and your color might not be within the detection range. Before following those steps, you can also try increasing the value of `PIXEL_COLOR_DIFF_THRESHOLD` in the `Constants.py` file to 10 or even higher if needed. This will expand your detection range, but if you want to find the exact number needed, I recommend following the previous steps.
