### ISSUE TITLE
Macro presses home too long and sets switch to sleep mode

### ISSUE THREAD

**Issue by SNIELSEL** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#36]
Sometimes when returning to home menu to reset it holds the home button to long causing the settings overlay to pop and because the first option is sleep it wil put the switch in sleep mode.

Should be able to get fixed if you implement another check or make the home menubpress shorter.

**Comment by SoaringEagle93** [comment]
I have been having this happen as well. I would let the program run over night and the next morning the program would be doing nothing and my switch was off. Upon turning it on I was in the start of the battle where normally the program would close the app. Wasn't sure what was going on until I just started another hunt and it did it after 2 resets and I was able to watch it happen.

**Comment by Dinones** [comment]
I have just uploaded a new version of the program that solves this issue. The press time for the `HOME` button has been reduced from 0.2s to 0.05s. I will mark this thread as solved, but please reopen the case if you detect the issue persists.

In order to download the latest version, you can either clone the repository again git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git or update the current one git pull origin master in your local repository folder.
