### ISSUE TITLE
Game_Capture.py providing very buggy screen capture

### ISSUE THREAD

**Issue by COSMIC-HOUND** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#5]
Hey, I am using the linux virutal machine on windows 10. When I try to run Game_Capture.py, it comes out very glitchy and buggy. Either it's completely black, the image is corrupted, or the image is fine but it will not change frames at all. Here are examples of each of these. (Again, when it looks fine, such as in the first one, it would not change the frame no matter how much I would use the joycon, despite the FPS ranging from 2-6. However, when on the screenshot with the corrupted imagery, I could see some low fps movement, but the image just looks like... that...) 
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/148904498/cba537a8-be71-4686-bff7-af7174ac8b93)
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/148904498/3a47e9d5-0b95-4e2d-a89c-9476c5ea4f48)
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/148904498/aff7af80-12e7-49a3-8655-9d2f84a1d231)

**Comment by Dinones** [comment]
Hey! It seems to be something related to external factors to the code. May I ask you some questions:

- Did you setup the virtual machine following the tutorial on Github?
- How much RAM are you providing to the virtual machine?
- Which Linux distribution and version are you using?
- What capture card are you using (Brand + Model)?

**Comment by COSMIC-HOUND** [comment]
Hi, thanks for the response.
I just reinstalled it, and it worked with quite a slow framerate for a short amount of time after having a black screen for a little bit, before it froze again. As of right now, it is stuck on the black screen again. I think last time I forgot to run "sudo pip install -r Requirements.txt" but idk if that would change anything. Btw, here are the answers for your questions.
- Yes. 
- I gave it 4096 MB of RAM in the setup. 
- I am using xubuntu 20.04.6
- I believe the exact capture card I am using is the ezcap301 Pro by Y&H

**Comment by Dinones** [comment]
Hi, thanks for answering the questions. 
It seems the capture card is compatible and since you have followed the tutorial, everything should be working correctly.
Here is a video of the Video_Capture.py file running on my virtual machine:

https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/109595182/956617db-bb9f-48f4-8666-2378552edf11

As I'm not able to replicate the error, here are some ideas I have for why it's failing:

- Please, seems obvious, but check that the capture card and the HDMI are connected properly. 
- Maybe some driver of the card is not working correctly on the VM. Could you download the repository in your Windows 10/11 environment and try executing the Video_Capture.py file? _Note that you can execute this file in Windows because it's not related to the Switch controller but to the capturing window process. The final program must always be executed on Linux_. If it happens the same way, we can discard the bug is related to the Linux installation; thus, it will be related to the capture card.
- Do you have any way to test if the capture card is working properly, for example, using OBS or any other application? It could be that the capture card or the HDMI cable you are using are damaged.

**Comment by Dinones** [comment]
Yeah, it would be nice if you could also try OBS in the VM. It'll help me undestanding what happens. Thanks

**Comment by COSMIC-HOUND** [comment]
Hi, sorry for the late response. I have done some testing.

When I open it on Windows 10, it works for a little bit at 60 FPS before crashing. It gives this error:

[ WARN:0@23.868] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

Maybe it's because it was running at 60 FPS?

Anyways, for the OBS on Linux, it could not pick up my capture card at all, and the capture card's light did not turn green (which means it is recording). However, when I open the code on the VM, it is black, but the capture card's light is green, so that means it is actually sending a signal to something.  I tried it again by making sure I was using the correct video capture variable, and this time it was black and crashed after ~5 seconds and gave this error:

[ WARN:0] global /tmp/pip-req-build-afu9cjzs/opencv/modules/videoio/src/cap_v4l.cpp (1001) tryIoctl VIDEOIO(V4L2:/dev/video2): select() timeout.

**Comment by COSMIC-HOUND** [comment]
Alright, I fixed it I think. I changed my USB to a USB 2.0 port, changed the USB setting to 3.0 (IDK why that made it work but whatever) and followed these instructions. https://forums.raspberrypi.com/viewtopic.php?t=35689

It says "Corrupt JPEG data: premature end of data segment" but I don't think its giving any issues

**Comment by Dinones** [comment]
Nice! Thanks for the link. Then, is the issue 100% solved and the program working?

**Comment by COSMIC-HOUND** [comment]
Everything regarding the video capture seems to be working. I haven't gotten the main program to work because I dont think my bluetooth adapter is compatible with linux, so ill have to figure that :/ but thx for the help with this

**Comment by COSMIC-HOUND** [comment]
scratch that, i got it all working - just one more thing, i would suggest to add somewhere recommended colors for pokemon, if you wanted to : ) I'll close the post, again, thanks for the help!! :3

**Comment by COSMIC-HOUND** [comment]
hey actually one more thing, do you know why it spams the home button over and over instead of closing? i changed the homescreen to white too

**Comment by Dinones** [comment]
Hey! Happy to hear everything about the capture card as solved. Regarding the constant toggle of the home menu, try downloading the latest version of the repository; it should be working now.

Also, if you are having problems detecting the Azelf colors, see this image:
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/109595182/3651cc8e-d7f2-4a20-ab10-b20cd63e7232)
It's easier to distinguish between normal and shiny because the shiny one has a yellow body, whose color is not present in the normal one. Don't focus on the blue color of the head. Uxie would be the most difficult one, as it has the same yellow color in both forms, so it'd be better to focus on the orange head in this case...

**Comment by COSMIC-HOUND** [comment]
ty, i got it all working!!!
